      SUBROUTINE BLNLIN
C**********************************************************************C
C BLNLIN.FOR							       C
C  18/1-1992   Kompaniet Numerisk lyd				       C
C  Tonni F. Johansen						       C
C**********************************************************************C
C  Call and execute  Block 'NLIN'				       C
C    AKKURAT Nè DUMMY-FIL
C  Programmert etter Dhatt & Touzot, s.384			       C
C**********************************************************************C

      RETURN
      END
